# Generated by Django 6.0.3 on 2026-06-02 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loans",
            fields=[
                ("id_loan", models.AutoField(primary_key=True, serialize=False)),
                ("amount_lent", models.IntegerField(default=None)),
                ("apprentice_group", models.CharField(max_length=10)),
                ("justification_use", models.CharField(max_length=255)),
                ("return_date", models.DateField(default=datetime.date.today)),
                ("loan_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "Prestamos",
            },
        ),
    ]
