# Generated by Django 6.0.3 on 2026-04-05 06:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_consumablematerial_and_more"),
        ("users", "0008_alter_user_document_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loans",
            fields=[
                ("id_loan", models.AutoField(primary_key=True, serialize=False)),
                ("amount_lent", models.IntegerField(default=None)),
                ("apprentice_group", models.CharField(max_length=10)),
                ("justification_use", models.CharField(max_length=255)),
                ("return_date", models.DateField(default=datetime.date.today)),
                ("loan_date", models.DateField(auto_now_add=True)),
                (
                    "id_material",
                    models.ForeignKey(
                        db_column="id_material",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="products.consumablematerial",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "Prestamos",
            },
        ),
    ]
