# Generated by Django 6.0.3 on 2026-06-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loans",
            name="id_material",
            field=models.ForeignKey(
                db_column="id_material",
                on_delete=django.db.models.deletion.RESTRICT,
                to="products.consumablematerial",
            ),
        ),
    ]
