# Generated by Django 6.0.3 on 2026-07-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loans",
            name="state",
            field=models.CharField(
                choices=[("Activo", "Activo"), ("Finalizado", "Finalizado")],
                default="Activo",
                max_length=20,
            ),
        ),
    ]
