# Generated by Django 6.0.3 on 2026-07-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_loans_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="state",
            field=models.CharField(
                choices=[
                    ("Activo", "Activo"),
                    ("Finalizado", "Finalizado"),
                    ("Incompleto", "Incompleto"),
                ],
                default="Activo",
                max_length=20,
            ),
        ),
    ]
