# Generated by Django 6.0.3 on 2026-07-23 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_alter_loans_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loans",
            name="id_user",
        ),
        migrations.AddField(
            model_name="loans",
            name="id_receptor_user",
            field=models.ForeignKey(
                db_column="id_receptor_user",
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="prestamos_recibidos",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loans",
            name="id_responsable_user",
            field=models.ForeignKey(
                db_column="id_responsable_user",
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="prestamos_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
