# Generated by Django 6.0.3 on 2026-07-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0009_batch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="signed_ip_receptor",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP desde la que firmó el receptor.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loans",
            name="signed_ip_responsable",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP desde la que firmó el responsable.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loans",
            name="signed_ua_receptor",
            field=models.CharField(
                blank=True,
                help_text="User-Agent del navegador al firmar (receptor).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loans",
            name="signed_ua_responsable",
            field=models.CharField(
                blank=True,
                help_text="User-Agent del navegador al firmar (responsable).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="signotp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="signotp",
            name="loan",
            field=models.ForeignKey(
                help_text="Préstamo representativo del lote al que pertenece este OTP.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to="loans.loans",
            ),
        ),
    ]
