# Generated by Django 6.0.3 on 2026-07-28 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0011_add_signed_ip_ua_columns"),
        ("products", "0006_seed_fixed_returnable_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.UUIDField(db_index=True)),
                ("amount_lent", models.IntegerField()),
                ("apprentice_group", models.CharField(max_length=10)),
                ("justification_use", models.CharField(max_length=255)),
                ("return_date", models.DateField()),
                ("loan_date", models.DateField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de firma"),
                            ("committed", "Comprometido (Loans creado)"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("signed_at_responsable", models.DateTimeField(blank=True, null=True)),
                (
                    "signed_ip_responsable",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "signed_ua_responsable",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("signed_at_receptor", models.DateTimeField(blank=True, null=True)),
                (
                    "signed_ip_receptor",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "signed_ua_receptor",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("committed_loan_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Momento en que el borrador expira si no se firma."
                    ),
                ),
                (
                    "id_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_drafts",
                        to="products.consumablematerial",
                    ),
                ),
                (
                    "id_receptor_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_prestamos_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_responsable_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_prestamos_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by_receptor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_firmas_receptor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_firmas_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loan_drafts",
            },
        ),
    ]
