# Generated by Django 6.0.7 on 2026-08-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_add_loan_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='state',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], default='Interno', max_length=20),
        ),
    ]
