# Generated by Django 6.0.3 on 2026-08-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0013_alter_loans_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="loans",
            name="loan_types",
            field=models.CharField(
                choices=[("Interno", "Interno"), ("Externo", "Externo")],
                default="Interno",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loans",
            name="state",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Activo", "Activo"),
                    ("Finalizado", "Finalizado"),
                    ("Incompleto", "Incompleto"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
    ]
