# Generated by Django 6.0.3 on 2026-06-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConsumableMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sena_plate", models.CharField(max_length=20, null=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="materials/")),
                ("quantity", models.IntegerField(null=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("No Disponible", "No Disponible"),
                            ("Mantenimiento", "Mantenimiento"),
                            ("Traslado", "Traslado"),
                            ("En prestamo", "En prestamo"),
                            ("Baja", "Baja"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="products.brand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnableMaterial",
            fields=[
                (
                    "consumable",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="products.consumablematerial",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("serial", models.CharField(max_length=20, unique=True)),
                ("technical_sheet", models.FileField(upload_to="specs/")),
                ("dimensions", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
