# Generated by Django 6.0.3 on 2026-03-18 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_role_description_type_document_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Consumable_material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_sena", models.CharField(max_length=20, null=True, unique=True)),
                ("material_name", models.CharField(max_length=100)),
                ("image", models.ImageField(null=True, upload_to="")),
                ("quantity", models.IntegerField(null=True)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("No Disponible", "No Disponible"),
                            ("Mantenimiento", "Mantenimiento"),
                            ("En préstamo", "En préstamo"),
                            ("Baja", "Baja"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.CharField(max_length=255, null=True)),
                ("date_of_purchase", models.DateField(null=True)),
                ("ubication", models.CharField(max_length=100, null=True)),
                (
                    "id_brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="products.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Returnable_material",
            fields=[
                (
                    "id_material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="products.consumable_material",
                    ),
                ),
                ("model", models.CharField(max_length=100, null=True)),
                ("serial", models.CharField(max_length=20, null=True, unique=True)),
                ("technical_specifications", models.FileField(null=True, upload_to="")),
                ("dimensions", models.CharField(max_length=100, null=True)),
                (
                    "id_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="products.category",
                    ),
                ),
            ],
        ),
    ]
