# Generated by Django 6.0.3 on 2026-04-05 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("users", "0006_documenttype_rename_direction_user_accountable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumableMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sena_plate", models.CharField(max_length=20, null=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="materials/")),
                ("quantity", models.IntegerField(null=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("No Disponible", "No Disponible"),
                            ("Mantenimiento", "Mantenimiento"),
                            ("En prestamo", "En prestamo"),
                            ("Baja", "Baja"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="returnable_material",
            name="id_material",
        ),
        migrations.RemoveField(
            model_name="returnable_material",
            name="id_category",
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="ReturnableMaterial",
            fields=[
                (
                    "consumable",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="products.consumablematerial",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("serial", models.CharField(max_length=20, unique=True)),
                ("technical_sheet", models.FileField(upload_to="specs/")),
                ("dimensions", models.CharField(max_length=100, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="products.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consumablematerial",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="products.brand"
            ),
        ),
        migrations.AddField(
            model_name="consumablematerial",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="users.user"
            ),
        ),
        migrations.DeleteModel(
            name="Consumable_material",
        ),
        migrations.DeleteModel(
            name="Returnable_material",
        ),
    ]
