# Generated by Django 6.0.3 on 2026-05-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_consumablematerial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumablematerial",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
