# Generated by Django 6.0.3 on 2026-06-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumablematerial",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="materials/"),
        ),
        migrations.AlterField(
            model_name="returnablematerial",
            name="technical_sheet",
            field=models.FileField(blank=True, default="", upload_to="specs/"),
        ),
    ]
