# Generated by Django 6.0.3 on 2026-05-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_consumablematerial_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumablematerial",
            name="state",
            field=models.CharField(
                choices=[
                    ("Disponible", "Disponible"),
                    ("No Disponible", "No Disponible"),
                    ("Mantenimiento", "Mantenimiento"),
                    ("Traslado", "Traslado"),
                    ("En prestamo", "En prestamo"),
                    ("Baja", "Baja"),
                ],
                max_length=20,
            ),
        ),
    ]
