# Generated by Django 6.0.3 on 2026-07-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_is_active_to_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablematerial',
            name='technical_sheet',
            field=models.FileField(blank=True, default='', upload_to='specs/consumables/'),
        ),
    ]
