# Generated by Django 6.0.3 on 2026-07-29 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_seed_fixed_returnable_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Archivo de la ficha técnica (PDF, Excel o PNG).",
                        upload_to="specs/returnables/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        help_text="Material al que pertenece esta ficha técnica.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_sheets",
                        to="products.consumablematerial",
                    ),
                ),
            ],
            options={
                "db_table": "technical_sheets",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
