# Generated by Django 6.0.3 on 2026-07-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_add_technical_sheet_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnablematerial",
            name="serial",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
