# Generated by Django 6.0.3 on 2026-08-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_returnablematerial_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablematerial',
            name='serial',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
