# Generated by Django 6.0.3 on 2026-08-04 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_consumablematerial_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablematerial',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.brand'),
        ),
    ]
