# Generated by Django 6.0.3 on 2026-03-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="type_document",
            name="description",
            field=models.CharField(max_length=225, null=True),
        ),
    ]
