# Generated by Codex on 2026-03-18

from django.db import migrations, models


DOCUMENT_CODES = ("CC", "TI", "CE", "PPT", "PPE")


def forwards_copy_type_document(apps, schema_editor):
    User = apps.get_model("users", "User")
    TypeDocument = apps.get_model("users", "Type_document")

    id_to_code = {
        td.id: (td.name or "").strip().upper() for td in TypeDocument.objects.all()
    }

    for user in User.objects.all():
        code = id_to_code.get(user.type_document_id)
        user.type_document_code = code if code in DOCUMENT_CODES else None
        user.save(update_fields=["type_document_code"])


def backwards_restore_type_document(apps, schema_editor):
    User = apps.get_model("users", "User")
    TypeDocument = apps.get_model("users", "Type_document")

    for code in DOCUMENT_CODES:
        TypeDocument.objects.get_or_create(name=code)

    code_to_id = {
        (td.name or "").strip().upper(): td.id for td in TypeDocument.objects.all()
    }

    for user in User.objects.all():
        code = (user.type_document_code or "").strip().upper()
        if code in code_to_id:
            user.type_document_id = code_to_id[code]
            user.save(update_fields=["type_document_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role_description_type_document_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type_document_code",
            field=models.CharField(
                choices=[
                    ("CC", "CC"),
                    ("TI", "TI"),
                    ("CE", "CE"),
                    ("PPT", "PPT"),
                    ("PPE", "PPE"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.RunPython(forwards_copy_type_document, backwards_restore_type_document),
        migrations.RemoveField(
            model_name="user",
            name="type_document",
        ),
        migrations.DeleteModel(
            name="Type_document",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="type_document_code",
            new_name="type_document",
        ),
        migrations.AlterField(
            model_name="user",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("CC", "CC"),
                    ("TI", "TI"),
                    ("CE", "CE"),
                    ("PPT", "PPT"),
                    ("PPE", "PPE"),
                ],
                max_length=3,
            ),
        ),
    ]
