# Generated by Django 6.0.3 on 2026-03-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role_description_type_document_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number_document",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="second_phonenumber",
            field=models.BigIntegerField(null=True),
        ),
    ]
