# Generated by Codex on 2026-03-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_number_document_alter_user_phone_number_and_more"),
        ("users", "0003_type_document_enum"),
    ]

    operations = []
