# Generated by Django 6.0.3 on 2026-07-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_deleted_at_user_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 del token JWT en crudo. Nunca se guarda el token completo.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Momento en que el token expira según su claim 'exp'. Usado por el comando de limpieza para descartar entradas obsoletas."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Token en lista negra",
                "verbose_name_plural": "Tokens en lista negra",
                "db_table": "blacklisted_tokens",
            },
        ),
    ]
