# Generated by Django 6.0.3 on 2026-04-05 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_role_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="direction",
            new_name="accountable",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="date_end",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="date_start",
            new_name="start_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="institutional_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="number_document",
        ),
        migrations.RemoveField(
            model_name="user",
            name="second_phonenumber",
        ),
        migrations.RemoveField(
            model_name="user",
            name="type_document",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(default="N/A", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="document_number",
            field=models.CharField(default="0", max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="N/A", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="second_phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="user",
            name="document_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="users.documenttype",
            ),
        ),
    ]
