# Generated by Django 6.0.3 on 2026-07-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_seed_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_instructor_planta',
            field=models.BooleanField(default=False, help_text='Indica si el usuario es instructor de planta.'),
        ),
    ]
