# Generated by Django 6.0.3 on 2026-04-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_documenttype_rename_direction_user_accountable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="document_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
