# Generated by Django 6.0.3 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_is_instructor_planta"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivation_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
