# Generated by Django 6.0.3 on 2026-04-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_document_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="document_number",
            field=models.CharField(default="0", max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
