# Generated by Django 6.0.3 on 2026-07-28 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_deactivation_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordChangeOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA-256 del código OTP. Nunca se almacena en claro.",
                        max_length=64,
                    ),
                ),
                (
                    "pending_password_hash",
                    models.CharField(
                        help_text="Hash Django de la nueva contraseña. Se aplica al confirmar el OTP.",
                        max_length=128,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_change_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP de cambio de contraseña",
                "verbose_name_plural": "OTPs de cambio de contraseña",
                "db_table": "password_change_otps",
            },
        ),
    ]
