# Generated by Django 6.0.3 on 2026-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_add_password_change_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_primary_admin",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este usuario es el superadministrador primigenio del sistema. No se puede quitar, cambiar de grupo ni desactivar a través de la API.",
            ),
        ),
    ]
