# Generated by Django 6.0.3 on 2026-05-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_documenttype_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="status",
            new_name="is_status",
        ),
    ]
