# Generated by Django 6.0.3 on 2026-07-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_add_is_primary_admin_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Si es True, el usuario debe cambiar su contraseña antes de usar el sistema.",
            ),
        ),
    ]
