# Generated by Django 6.0.3 on 2026-05-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_rename_status_user_is_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_status",
            new_name="is_active",
        ),
    ]
