# Generated by Django 6.0.3 on 2026-05-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_is_status_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="institutional_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
