# Generated by Django 6.0.3 on 2026-07-29 23:15

from django.db import migrations, models


def migrate_accountable_to_flag(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        legacy = getattr(user, "accountable", None)
        if legacy and str(legacy).strip():
            user.is_accountable = True
            user.save(update_fields=["is_accountable"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_accountable",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario puede ser asignado como cuentadante de materiales.",
            ),
        ),
        migrations.RunPython(migrate_accountable_to_flag, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="accountable",
        ),
    ]
