# Generated by Django 6.0.3 on 2026-07-28 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre completo del actor al momento del evento.",
                        max_length=100,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("users", "Usuarios"),
                            ("consumables", "Materiales Consumibles"),
                            ("returnables", "Materiales Devolutivos"),
                            ("brands", "Marcas"),
                            ("loans", "Préstamos"),
                            ("returns", "Devoluciones"),
                            ("tasks", "Tareas"),
                            ("auth", "Autenticación"),
                            ("permissions", "Permisos / Grupos"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Creación"),
                            ("UPDATE", "Modificación"),
                            ("DELETE", "Eliminación"),
                            ("TOGGLE_ACTIVE", "Activar / Desactivar"),
                            ("RESTORE", "Restauración"),
                            ("LOGIN", "Inicio de sesión"),
                            ("LOGOUT", "Cierre de sesión"),
                            ("PASSWORD_CHANGE", "Cambio de contraseña"),
                            ("PASSWORD_RESET", "Restablecimiento de contraseña"),
                            ("ASSIGN_GROUP", "Asignación de grupo"),
                            ("REMOVE_GROUP", "Remoción de grupo"),
                            ("ASSIGN_PERM", "Asignación de permiso"),
                            ("REMOVE_PERM", "Remoción de permiso"),
                            ("SIGN_LOAN", "Firma de préstamo"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="PK del objeto afectado.", null=True
                    ),
                ),
                (
                    "target_repr",
                    models.CharField(
                        blank=True,
                        help_text="Descripción del objeto afectado (nombre, email, etc.).",
                        max_length=200,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        help_text="Detalle adicional: campos modificados, motivo, observaciones.",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP del cliente que originó la acción.",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que ejecutó la acción. Null si fue el sistema.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de auditoría",
                "verbose_name_plural": "Historial de auditoría",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
