# Generated by Django 6.0.3 on 2026-04-05 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
        ("products", "0002_consumablematerial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanReturn",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("leftover_quantity", models.IntegerField(null=True)),
                ("observations", models.CharField(max_length=255)),
                ("return_date", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="loans.loans"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="products.consumablematerial",
                    ),
                ),
            ],
            options={
                "db_table": "Retornos_prestamo",
            },
        ),
    ]
