# Generated by Django 6.0.3 on 2026-07-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanreturn",
            name="returned_quantity",
            field=models.IntegerField(null=True),
        ),
    ]
