# Django settings for sia_api project.
#
# Generated by 'django-admin startproject' using Django 6.0.3.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _split_env_list(value):
    # Convierte "a,b,c" en una lista limpia.
    # Nos evita errores por espacios o comas extra.
    return [item.strip() for item in value.split(",") if item.strip()]

# SECURITY WARNING: keep the secret key used in production secret!
# Clave secreta usada por Django para firmar sesiones.
# Para desarrollo local usamos un fallback seguro si no hay variable de entorno.
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-secret-key-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
# Activa el modo debug para ver errores detallados.
# En produccion deberia ir en False.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Lista de hosts permitidos.
# Si el host no esta aqui, Django rechaza la peticion.
ALLOWED_HOSTS = _split_env_list(os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1'))
if "locahost" in ALLOWED_HOSTS and "localhost" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("localhost")
if DEBUG:
    for host in ("localhost", "127.0.0.1"):
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'coreapi',
    'django_filters',


    #Apps de django
    'modules.home',
    'modules.users',
    'modules.permissions',
    'modules.products',
    'modules.loans',
    'modules.returns',
    'modules.tasks',
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sia_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sia_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Conexion a base de datos tomada del .env.
# Si no se define, usamos SQLite para desarrollo local.
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE') or 'django.db.backends.sqlite3',
        'NAME': os.getenv('DB_NAME') or str(BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK={
        'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',

        # Quien valida el token en cada peticion 
        'DEFAULT_AUTHENTICATION_CLASSES': [
            'modules.users.authentication.JWTAuthentication',
        ],

        # Por defecto, TODAS las rutas exigen estar autenticado
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.IsAuthenticated',
        ],

        # Backends de filtrado globales: django-filter para filtros exactos/rango,
        # SearchFilter para búsqueda libre de texto, OrderingFilter para ordenación.
        'DEFAULT_FILTER_BACKENDS': [
            'django_filters.rest_framework.DjangoFilterBackend',
            'rest_framework.filters.SearchFilter',
            'rest_framework.filters.OrderingFilter',
        ],

}

# Origenes permitidos para llamadas desde el navegador.
# Si faltan, el frontend se bloquea por CORS.
CORS_ALLOWED_ORIGINS = _split_env_list(
    os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173')
)

# Origenes confiables para CSRF en formularios y POST.
# Si faltan, Django puede responder 403.
CSRF_TRUSTED_ORIGINS = _split_env_list(
    os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173')
)
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Archivos subidos por usuarios (imagenes, documentos, etc).
# MEDIA_ROOT: carpeta donde se guardan fisicamente en el servidor.
# MEDIA_URL: prefijo de la URL para acceder a ellos desde el navegador.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# URL base del frontend.
# Se usa para construir enlaces que se envian por correo (ej. reset de contrasena).
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Configuracion de correo.
# Por defecto usamos el backend de consola: los correos NO se envian,
# se imprimen en la terminal donde corre el servidor. Ideal para desarrollo.
# En produccion, define EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# junto con EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, etc.
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@sia.local')
