# Generated by Django 6.0.3 on 2026-07-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0004_add_missing_viewset_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el grupo está activo. Los grupos inactivos no pueden recibir nuevos usuarios.",
            ),
        ),
    ]
