# Generated by Django 6.0.3 on 2026-03-18 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=245)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=245)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('number_document', models.IntegerField(unique=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('direction', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('second_phonenumber', models.IntegerField(null=True)),
                ('institutional_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.role')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.typedocument')),
            ],
        ),
    ]
