# Generated by Django 6.0.3 on 2026-04-05 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0008_alter_user_document_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[("Activa", "Activa"), ("Inactiva", "Inactiva")],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "Tareas",
            },
        ),
    ]
