# Generated by Django 6.0.3 on 2026-06-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[("Activa", "Activa"), ("Inactiva", "Inactiva")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "Tareas",
            },
        ),
    ]
