export const returnablesReportConfig = {
    reportTitle: "Reporte de Materiales Devolutivos",
    fileNamePrefix: "reporte-devolutivos",
    fields: [
        { key: "sena_plate",   label: "Placa SENA",    default: true  },
        { key: "name",         label: "Nombre",         default: true  },
        { key: "brand.name",   label: "Marca",          default: true  },
        { key: "category.name",label: "Categoría",      default: true  },
        { key: "model",        label: "Modelo",         default: true  },
        { key: "serial",       label: "Serial",         default: true  },
        {
            key: "user",
            label: "Cuentadante",
            default: true,
            accessor: (row) => row.user ? `${row.user.first_name} ${row.user.last_name}` : "-",
        },
        { key: "dimensions",   label: "Dimensiones",    default: true  },
        { key: "state",        label: "Estado",         default: true  },
        { key: "quantity",     label: "Cantidad",       default: false },
        { key: "unit_price",   label: "Valor unitario", default: false },
        { key: "total_price",  label: "Valor total",    default: false },
        { key: "purchase_date",label: "Fecha compra",   default: false },
        { key: "is_active",    label: "Activo",         default: false },
    ],
};
